minishift/minishift-ci-jobs

minishift-ci-index.yaml

Issue #2 Update JJB for minishift-b2d-iso job

---

minishift-ci-index.yaml

Fix #4 
Also decrease timeout to 20 mins

Issue #4 Update JJB for minishift job

---

minishift-ci-index.yaml

Add a github token to the credential store

---

minishift-ci-index.yaml

Issue #16 Enable CI to get triggered when a push to master occurs

---

minishift-ci-index.yaml

Issue #18 Change the name of build master and pull request jobs

---

minishift-ci-index.yaml

Issue #22 Add retry count while getting node

---

minishift-ci-index.yaml

Issue #24 Increased timeout to 30 mins

---

minishift-ci-index.yaml

Issue #26 Updated retry count and handle error message properly

---

minishift-ci-index.yaml

- send notification to minishift mail list

Issue #41 replace nightly build notification email with minishfit mail list address

---

minishift-ci-index.yaml

Issue #43 Disable cron job for minishift-nightly-job

---

minishift-ci-index.yaml

* Also removed `minishift-nightly-job` template. 
@LalatenduMohanty Disabled minikube nightly job notification

Disable minikube notification till issue Minishift#1857 is fixed

---

cico_pr_test.sh

add a script to test and validate the changes to minishift-ci-index.yaml

Add jenkins-jobs test for validating minishift-ci-index.yaml

---

minishift-ci-index.yaml

Add a jenkins job on minishift-ci-index.yaml for validating the changes comes via PR

Add job to validate PR 

---

minishift-ci-index.yaml

Needed for https://github.com/minishift/minishift-centos-iso/issues/178

Add minishift CentOS ISO release job

---

minishift-ci-index.yaml

Issue #49 Individual recipients for nightly job build failure mails

---

minishift-ci-index.yaml

Issue #54 Add PR and nightly job for minishift-addons

---

minishift-ci-index.yaml

Issue #61 Update nightly time

---

minishift-ci-index.yaml

Issue #65 remove minikube iso and extra b2d iso nightly job

---

minishift-ci-index.yaml

Add email notification for master and release CI job failures

---

minishift-ci-index.yaml

Issue #76 Add minishift-knative jobs

---

minishift-ci-index.yaml

Issue #79 Add credential binding for redhat registry login

---

minishift-ci-index.yaml

Fix for #81 
Signed-off-by: Tomáš Sedmík <tsedmik@redhat.com>

Issue #81 - Add @tsedmik and @jsliacan to Git Hub PR admins

---

minishift-ci-index.yaml

Add temporary code-ready containers jobs

---

minishift-ci-index.yaml

Issue #87 Bind crc bundle password to CRC_BUNDLE_PASSWORD

---

minishift-ci-index.yaml

Issue #93 Fix the credential id for CRC_PULL_SECRET

---

minishift-ci-index.yaml

Remove people who are no longer part of the team, and add Guillaume.

Update admin list
